- name: "Install Apache"
  apt:
    name: apache2
    state: present

- name: "Apache Install confrmation message"
  debug:
    msg: "System {{ inventory_hostname }} has installed}}"

- name: "Start Apache"
  service:
    name: apache2
    state: started

- name: "Copy index file"
  copy:
    src: apace_index.html
    dest: /var/www/html/index.html
  notify: "restart apache"
